package com.biocare.authority.bean;

public class Template {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.id
     *
     * @mbggenerated Thu Jul 27 15:52:05 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_name
     *
     * @mbggenerated Thu Jul 27 15:52:05 CST 2017
     */
    private String templateName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.id
     *
     * @return the value of template.id
     *
     * @mbggenerated Thu Jul 27 15:52:05 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.id
     *
     * @param id the value for template.id
     *
     * @mbggenerated Thu Jul 27 15:52:05 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_name
     *
     * @return the value of template.template_name
     *
     * @mbggenerated Thu Jul 27 15:52:05 CST 2017
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_name
     *
     * @param templateName the value for template.template_name
     *
     * @mbggenerated Thu Jul 27 15:52:05 CST 2017
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }
}