package com.biocare.platform.service.impl;

import com.alibaba.fastjson.JSON;
import com.biocare.platform.bean.TemplateTable;
import com.biocare.platform.query.TemplateTablePageQuery;
import com.biocare.platform.service.TemplateTableService;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import javax.annotation.Resource;
import java.util.Date;
import java.util.List;
import java.util.UUID;

/**
 * Service测试-模板表
 * generated By EasyFrame
 * @author ChenRenhao
 * @version 1.0
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = {"classpath:spring/spring-global.xml"})
public class TemplateTableServiceImplTest {

    Logger logger = LoggerFactory.getLogger(TemplateTableServiceImplTest.class);

    @Resource
    private TemplateTableService templateTableService;

    @Test
    public void crudTest() throws Exception {
        TemplateTable templateTable = new TemplateTable();
        String pk = UUID.randomUUID().toString().replace("-","");
        templateTable.setTemplateId(pk);
        templateTable.setTemplateInt(250);
        templateTable.setTemplateDouble(2.50);
        templateTable.setTemplateString("字符串");
        templateTable.setTemplateDate(new Date());

        templateTableService.saveSelective(templateTable);
        System.out.println("新增成功:"+pk);

        templateTable.setTemplateInt(500);
        templateTable.setTemplateDouble(5.00);
        templateTable.setTemplateString("字符串-更新");
        templateTable.setTemplateDate(new Date());
        templateTableService.modifyById(templateTable);
        System.out.println("更新成功");

        TemplateTablePageQuery pageQuery = new TemplateTablePageQuery();
        pageQuery.setPage(0);
        pageQuery.setPageSize(10);
        List<TemplateTable> templateTableList= (List<TemplateTable>)templateTableService.queryDynamic(pageQuery).getData();
        System.out.println("查询成功:"+JSON.toJSONString(templateTableList));

        templateTableService.removeById(pk);
        System.out.println("删除成功");
    }


}
